version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=intraway.com --logLevel=DEBUG
    networks:
      - gateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  gateway:
    driver: bridge
